version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Especifica la versión de Python
    commands:
      - echo "Instalando dependencias..."
      - python -m pip install --upgrade pip
      - pip install pytest flake8 bandit
      
  pre_build:
    commands:
      - echo "Ejecutando verificaciones previas..."
      - python --version
      - pip list
      
  build:
    commands:
      - echo "Ejecutando pipeline Sky20..."
      - echo "Ejecutando tests..."
      - pytest --verbose || exit 1  # Falla si hay errores en tests
      - echo "Ejecutando linting..."
      - flake8 . --max-line-length=88 || exit 1  # Falla si hay errores de estilo
      - echo "Ejecutando escaneo de seguridad..."
      - bandit -r . -f json -o bandit-report.json || exit 1  # Falla si hay vulnerabilidades críticas
      - echo "Pipeline completado correctamente."
      
  post_build:
    commands:
      - echo "Limpieza y reportes finales..."
      - echo "Build completado el $(date)"

artifacts:
  files:
    - bandit-report.json
  name: sky20-security-report
